name: sun_stickers
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  font_awesome_flutter: ^10.4.0
  badges: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/fonts/AppIcon.ttf

